# Generated by Django 4.2.21 on 2025-05-25 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='模式标题')),
                ('description', models.TextField(verbose_name='模式描述')),
                ('content', models.TextField(verbose_name='详细内容')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面图片')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签（用逗号分隔）')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patterns.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '设计模式',
                'verbose_name_plural': '设计模式',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatternFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('file', models.FileField(upload_to='pattern_files/', verbose_name='文件')),
                ('description', models.TextField(blank=True, verbose_name='文件描述')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='patterns.designpattern', verbose_name='所属模式')),
            ],
            options={
                'verbose_name': '模式文件',
                'verbose_name_plural': '模式文件',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
