# Generated by Django 4.2.21 on 2025-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designpattern',
            name='content_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='详细内容JSON'),
        ),
    ]
